service: ec2security

provider:
  name: aws
  endpointType: REGIONAL  
  runtime: nodejs12.x
  region: ${self:custom.region}

custom:
  serverless-offline:
    port: 4000
  region: ${opt:region, 'ap-southeast-2'} 

environment:
  region: ${self:custom.region}
  apiVersion: "2016-11-15"

functions:
  list:
    events:
      - http:
          path: securitygroups
          method: get    
    handler: src/handlers/securityGroups.list

plugins: 
  - serverless-offline

